services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    image: antiplag-api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - file-storing-service
      - file-analysis-service
    environment:
      STORAGE_SERVICE_URL: http://file-storing-service:8081
      ANALYSIS_SERVICE_URL: http://file-analysis-service:8082

  file-storing-service:
    build: ./file-storing-service
    container_name: file-storing-service
    image: antiplag-file-storing-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - db-storing
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-storing:5432/file_info
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      STORAGE_SERVICE_URL: http://file-storing-service:8081
      STORAGE_PATH: uploads
    volumes:
      - ./uploads:/app/uploads

  file-analysis-service:
    build: ./file-analysis-service
    container_name: file-analysis-service
    image: antiplag-file-analysis-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - file-storing-service
      - db-analysis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-analysis:5432/analysis_info
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      STORAGE_PATH: pics
    volumes:
      - ./pics:/app/pics

  db-storing:
    image: postgres:16
    container_name: db-storing
    restart: always
    environment:
      POSTGRES_DB: file_info
      POSTGRES_USER: postgres # default username for PostgreSQL - change as needed
      POSTGRES_PASSWORD: postgres # default password for PostgreSQL - change as needed
    ports:
      - "5433:5432"
    volumes:
      - pgdata_storing:/var/lib/postgresql/data

  db-analysis:
    image: postgres:16
    container_name: db-analysis
    restart: always
    environment:
      POSTGRES_DB: analysis_info
      POSTGRES_USER: postgres # default username for PostgreSQL - change as needed
      POSTGRES_PASSWORD: postgres # default password for PostgreSQL - change as needed
    ports:
      - "5434:5432"
    volumes:
      - pgdata_analysis:/var/lib/postgresql/data

volumes:
  pgdata_storing:
  pgdata_analysis: