server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file_info
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

storage:
  path: uploads